/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


DROP DATABASE IF EXISTS `grupo04`;
CREATE DATABASE `grupo04` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `grupo04`;
DROP TABLE IF EXISTS `editorial`;
CREATE TABLE `editorial` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

INSERT INTO `editorial` VALUES (1,'Grupo Editorial EDISAL');
INSERT INTO `editorial` VALUES (2,'ESE Ediciones');
INSERT INTO `editorial` VALUES (3,'Santillana');
INSERT INTO `editorial` VALUES (4,'Piedra Santa');
DROP TABLE IF EXISTS `libro`;
CREATE TABLE `libro` (
  `isbn` bigint(13) NOT NULL AUTO_INCREMENT,
  `titulo` varchar(255) NOT NULL DEFAULT '',
  `autor` varchar(255) NOT NULL DEFAULT '',
  `editorial` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`isbn`)
) ENGINE=InnoDB AUTO_INCREMENT=4444444444442 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

INSERT INTO `libro` VALUES (1111111111111,'prueba','Alexander',1);
INSERT INTO `libro` VALUES (1111111111114,'fffff','Disney  ',4);
INSERT INTO `libro` VALUES (1111111111115,'Blanca nieves','Alexander',3);
INSERT INTO `libro` VALUES (1111111111116,'si se puede','YO',3);
INSERT INTO `libro` VALUES (4444444444441,'prueba','Alexander',2);

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
