/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


DROP DATABASE IF EXISTS `grupo04`;
CREATE DATABASE `grupo04` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `grupo04`;
DROP TABLE IF EXISTS `libro`;
CREATE TABLE `libro` (
  `id` int(13) NOT NULL AUTO_INCREMENT,
  `isbn` varchar(255) NOT NULL DEFAULT '',
  `titulo` varchar(255) NOT NULL DEFAULT '',
  `autor` varchar(255) NOT NULL DEFAULT '',
  `editorial` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

INSERT INTO `libro` VALUES (1,'1111111243424','La odisea','Kevin','Renacimiento');
INSERT INTO `libro` VALUES (2,'1111111111111','Romeo y Julieta','Kevin','Santillana');
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(255) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `nombre` varchar(255) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `nivel` varchar(255) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `password` varchar(255) CHARACTER SET latin1 NOT NULL DEFAULT '',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

INSERT INTO `users` VALUES (1,'kevin','Kevin','1','1234');
INSERT INTO `users` VALUES (2,'navarro','Navarro','1','1234');
INSERT INTO `users` VALUES (3,'alexander','Alexander','2','1234');

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
